name: Build and Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build without tests
        run: ./gradlew clean build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            PID=$(lsof -t -i :8080)
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi

            export DB_URL=${{ secrets.DB_URL }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export FRONTEND_REDIRECT_URL=${{ secrets.FRONTEND_REDIRECT_URL }}

            export KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            export KAKAO_TOKEN_URI=${{ secrets.KAKAO_TOKEN_URI }}
            export KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}

            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
            export GOOGLE_AUTH_URI=${{ secrets.GOOGLE_AUTH_URI }}
            export GOOGLE_TOKEN_URI=${{ secrets.GOOGLE_TOKEN_URI }}
            export GOOGLE_USER_INFO_URI=${{ secrets.GOOGLE_USER_INFO_URI }}

            export FILE_UPLOAD_DIR=${{ secrets.FILE_UPLOAD_DIR }}
            export FILE_MAX_SIZE=${{ secrets.FILE_MAX_SIZE }}
            export FILE_ALLOWED_EXTENSIONS=${{ secrets.FILE_ALLOWED_EXTENSIONS }}
            export FILE_BASE_URL=${{ secrets.PROD_FILE_BASE_URL }}
            
            export SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}
            export SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
            export SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}

            nohup java -jar /home/ubuntu/app/build/libs/darkmap-0.0.1-SNAPSHOT.jar > /home/ubuntu/app/app.log 2>&1 &
